### ISSUE TITLE
How to get access and refresh tokens?

### ISSUE THREAD

**Issue by bebjakub** [azmicirit/sumup-react-native-bridge#1]
Hello,
https://github.com/azmicirit/sumup-react-native-bridge/blob/master/example/src/TestScreen.tsx#L16 I get apiKey from the dashboard. But how to get access and refresh tokens? 
I spend a few hours with https://developer.sumup.com/docs/authorization already :)
Thank you!

**Comment by azmicirit** [comment]
SumUp uses OAuth 2.0 protocol to provide access token. Users need to give you an authorisation via your web page before you get an access token from SumUp. To generate that web page, you should call this route:

```
curl --request GET \
  --url 'https://api.sumup.com/authorize?response_type=code&client_id=fOcmczrYtYMJ7Li5GjMLLcUeC9dN&redirect_uri=https://sample-app.example.com/callback&scope=payments user.app-settings transactions.history user.profile_readonly&state=2cFCsY36y95lFHk4'
```

After that, you can call api to get an access token.

```
curl -X POST \
  https://api.sumup.com/token \
  -H 'Content-Type: application/x-www-form-urlencoded' \
  -d 'grant_type=authorization_code'\
  -d 'client_id=fOcmczrYtYMJ7Li5GjMLLcUeC9dN'\
  -d 'client_secret=717bd571b54297494cd7a79b491e8f2c1da6189c4cc2d3481380e8366eef539c' \
  -d 'code=be366ce9fccd0c337d1da29b31d06dd1135ab95401562883'
```

This call will provide an access token and refresh token so you can generate new access token with refresh token once your access token is expired or invalid (delete, logout, etc)

Payments scope is disabled by default so your application can't start a transaction on behalf of users. Please contact with SumUp to enable payments scope if you plan to use that feature.
[https://cloud.crm.sumup.com/sumup-developers-contact-form](https://cloud.crm.sumup.com/sumup-developers-contact-form)

**Comment by bebjakub** [comment]
@azmicirit thank you for the prompt answer!
I'm working on a simple iOS app, I would like to just create a screen to select the amount to donate via card reader. 

Currently I'm not able to get **code** from 
`https://api.sumup.com/authorize?response_type=code&client_id=<CLIENT_ID>&redirect_uri=com.myapp://callback`. Only http redirect_uri returns **code** for me, but still I need some way to push **code** back to the iOS app.

I also tried [client credentials flow](https://developer.sumup.com/docs/authorization/#client-credentials-flow) that returns access_token, but SumupSDK.login(access_token) is not working, I get:
`
{"code": 20, "invalidToken": true, "message": "Sorry, but we've experienced an unexpected error. Please try closing the app and logging in again, or contact our Support Team", "success": false}
`.

What do you suggest?
Thank you!

**Comment by azmicirit** [comment]
Client Credentials flow does not support payments.
If you got a code from /authorize flow then you could call /token to get access token. Please check body of **redirect_uri=<APP_URL>** response. Don't forget to register the url scheme on Xcode

**Comment by bebjakub** [comment]
@azmicirit Thanx, It's running!
